# Generated by Django 5.0.2 on 2024-02-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_socialapps_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
