# Generated by Django 5.0.2 on 2024-02-13 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='polls.category'),
            preserve_default=False,
        ),
    ]
