# Generated by Django 5.0.2 on 2024-02-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_library_category_book_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
