# Generated by Django 5.0.2 on 2024-02-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
