# Generated by Django 5.0.2 on 2024-02-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.CharField(choices=[('Boshlang`ich', 'Boshlang`ich'), ('Havaskor', 'Havaskor'), ('Professional', 'Professional')], default='Boshlang`ich', max_length=12),
        ),
    ]
