# Generated by Django 5.0.2 on 2024-02-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_book_basket_book_image_remove_basket_books_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legimitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=9)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
