# Generated by Django 5.0.2 on 2024-02-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_status_course_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course'),
            preserve_default=False,
        ),
    ]
