# Generated by Django 5.0.2 on 2024-02-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_chapter_chapter_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course',
            new_name='chapter',
        ),
    ]
